import os

TWELVE_DATA_API_KEY = os.getenv("TWELVE_DATA_API_KEY")

SYMBOL = "EUR/USD"
INTERVAL = "5min"

EMA_FAST = 20
EMA_SLOW = 50
RSI_PERIOD = 14
ATR_PERIOD = 14

CANDLE_LIMIT = 120

# Проверяем рынок раз в 5 минут
CHECK_INTERVAL_SECONDS = 300
# Strategy filters
MIN_EMA_DISTANCE_ATR = 0.15
MIN_ATR = 0.00010

RSI_BUY_MIN = 52
RSI_BUY_MAX = 68

RSI_SELL_MIN = 32
RSI_SELL_MAX = 48
